version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  bundle:
  db_data:
